goalpoolapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'goalpoolapp'
urlpatterns = [
    # index view
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    # sign up and login views
    path('register', views.register, name='register'),
    path('loginuser', views.loginuser, name='loginuser'),
    path('logoutuser', views.logoutuser, name='logoutuser'),
    # main dashboard view
    path('dashboard', views.dashboard, name='dashboard'),
    # draft league views
    path('createleague', views.createleague, name='createleague'),
    path('joinleague', views.joinleague, name='joinleague'),
    path('startdraft <int:leagueid>', views.startdraft, name='startdraft'),
    path('draft <int:leagueid>', views.draft, name='draft'),
    path('draft/', views.draft, name='draft'),
    # global league views
    path('pickplayer', views.pickplayer, name='pickplayer'),
    path('globalleague', views.globalleague, name='globalleague'),
    path('createglobalteam', views.createglobalteam, name='createglobalteam'),
    path('playersearch', views.playersearch, name='playersearch'),
    path('globaltransfers', views.globaltransfers, name='globaltransfers'),
    path('viewglobalteam <int:team_id>', views.viewglobalteam, name='viewglobalteam'),
    # user settings view
    path('settings', views.settings.as_view(template_name="goalpoolapp/settings.html"), name='settings'),
    path('success', views.success, name='success'),
]

goalpoolproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("goalpoolapp.urls"))
]

goalpoolapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class User(AbstractUser):
    emailpermission = models.BooleanField(null=True)

class League(models.Model):
    teamlimit = models.IntegerField()
    leaguename = models.CharField(max_length=64)
    leaguecode = models.CharField(max_length = 10, blank=True, null=True)
    teamplayerslimit = models.IntegerField()
    transfersActivated = models.BooleanField(default=False)
    transfersAllowed = models.BooleanField(default=False)
    duplicatePlayersAllowed = models.BooleanField()
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name="administratedleague")
    draftcomplete = models.BooleanField(default=False)
    draftstarted = models.BooleanField(default=False)
    draftposition = models.IntegerField(default=1)
    draftdecending = models.BooleanField(default=False)

    def __str__(self):
        return self.leaguename

class Country(models.Model):
    countryname = models.CharField(max_length=20)
    countrypic = models.CharField(max_length=100)
    countryid = models.IntegerField()

    def create(countryname, countrypic, countryid):
        country = Country(countryname=countryname, countrypic=countrypic, countryid=countryid)
        return country

    def __str__(self):
        return self.countryname

class Player(models.Model):
    playercode = models.IntegerField()
    leagues = models.ManyToManyField(League, related_name="leagueplayers", blank=True)
    # firstname = models.CharField(max_length=64)
    # surname = models.CharField(max_length=64)
    nickname = models.CharField(max_length=64)
    goals = models.IntegerField(default=0)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="players")
    currentweekgoals = models.IntegerField(default=0)
    position = models.CharField(max_length=12)
    pic = models.CharField(max_length=100)

    def create(playercode, nickname, pic, position):
        player = Player(playercode=playercode, nickname=nickname, pic=pic, position=position)
        return player

    def __str__(self):
        return self.nickname

class Team(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name="managedteams")
    league = models.ForeignKey(League, on_delete=models.CASCADE, related_name="leagueteams")
    players = models.ManyToManyField(Player, related_name="teams", blank=True)
    provisionalplayers = models.ManyToManyField(Player, related_name="provisionalteams", blank=True)
    rank = models.IntegerField(default=1)
    teamname = models.CharField(max_length=64)
    totalgoals = models.IntegerField(default=0)
    draftnumber = models.IntegerField(blank=True, null=True)

    def create(manager, league, teamname):
        team = Team(manager=manager, league=league, teamname=teamname)
        return team

    def __str__(self):
        return f"{self.teamname}, {self.manager}, {self.league}"

class Fixture(models.Model):
    code = models.IntegerField()
    round = models.IntegerField()
    date = models.DateTimeField()
    hometeam = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="homefixture")
    awayteam = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="awayfixture")
    homescore = models.IntegerField(default=0)
    awayscore = models.IntegerField(default=0)
    homescorers = models.ManyToManyField(Player, related_name="homegamesscoredin", blank=True)
    awayscorers = models.ManyToManyField(Player, related_name="awaygamesscoredin", blank=True)
    finished = models.BooleanField(default=False)

    def create(code, round, date, hometeam, awayteam):
        fixture = Fixture(code=code, round=round, date=date, hometeam=hometeam, awayteam=awayteam, )
        return fixture

    def __str__(self):
        return f"{self.hometeam} vs {self.awayteam} on {self.date}"

class GlobalVars(models.Model):
    roundnumber = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.roundnumber}"

goalpoolapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

from .models import League, Team, User

class NewLeagueForm(ModelForm):
    class Meta:
        model = League
        fields = ["leaguename", "teamlimit", "teamplayerslimit", "duplicatePlayersAllowed", "transfersActivated", ]

class NewTeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ["teamname",]

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

goalpoolapp/views.py
# django imports
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator
from django.contrib.auth.password_validation import validate_password

# python imports
from uuid import uuid4
from fpl import FPL
from random import randint
from json import loads

# app imports
from .models import *
from .forms import NewLeagueForm, NewTeamForm, ChangePasswordForm
from .functions import *

# Create your views here.
# base page view
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'goalpoolapp/index.html', {
            'title': "Welcome",
    })
    else:
        return HttpResponseRedirect(reverse("goalpoolapp:dashboard"))

# registers a new user
def register(request):
    # shows register page when method is GET
    if request.method == 'GET':
        return render(request, 'goalpoolapp/register.html')
    # attempts to create and save user then the method is POST
    elif request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # make sure that passwords match
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "goalpoolapp/register.html", {
                "message": "Passwords must match."
            })
        try:
            validate_password(password, user=None, password_validators=None)
        except Exception as exception:
            print(exception)
            return render(request, "goalpoolapp/register.html", {
                "message": exception
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            try:
                request.POST["emailpermission"]
                user.emailpermission = True
            except:
                user.emailpermission = False
            user.save()
        except IntegrityError:
            return render(request, "goalpoolapp/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("goalpoolapp:index"))

# login view, renders the login page, and logs in the user if username and password match User model
def loginuser(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("goalpoolapp:index"))
        else:
            return render(request, "goalpoolapp/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "goalpoolapp/login.html")

# Logs out the user
def logoutuser(request):
    logout(request)
    return HttpResponseRedirect(reverse("goalpoolapp:index"))


# shows dashboard for user
@login_required
def dashboard(request):
    # displays all the teams and leagues user is a part of
    teams = Team.objects.filter(manager=request.user)
    leagues = League.objects.filter(leagueteams__in=teams)
    leagues = leagues.exclude(id='19')
    global_league_teams = League.objects.get(id='19').leagueteams.all()
    global_team = ""
    for team in global_league_teams:
        if team.manager == request.user:
            global_team = team
    players = Player.objects.filter(leagues__in=leagues).order_by('-goals')[:10]
    currentweek = GlobalVars.objects.first().roundnumber
    currentweekvar = Fixture.objects.filter(round=currentweek).order_by('date')
    nextweek = Fixture.objects.filter(round=(currentweek + 1)).order_by('date')
    return render(request, 'goalpoolapp/dashboard.html', {
        "teams": teams,
        "leagues": leagues,
        "players": players,
        "currentweek": currentweekvar,
        "nextweek": nextweek,
        "globalteam": global_team
    })

# create a league view, uses NewLEagueForm to create a new league
@login_required
def createleague(request):
    if request.method == "GET":
        return render(request, 'goalpoolapp/createleague.html', {
            "form": NewLeagueForm(),
        })
    else:
        # sets message as blank
        message = ''
        # gets and checks data from NewleagueForm is valid
        league_form = NewLeagueForm(data=request.POST)
        if league_form.is_valid() and "teamname" in request.POST:
            teamname = request.POST["teamname"]
            if teamname == "":
                message = f"Please input team name"
                return render(request, 'goalpoolapp/createleague.html', {
                    "message": message,
                    "form": NewLeagueForm(),
                    })
            players = Player.objects.all()
            # creates a League model from form data
            league = league_form.save(commit=False)
            players = Player.objects.all()
            if league.teamlimit * league.teamplayerslimit > len(players):
                return render(request, 'goalpoolapp/createleague.html', {
                    "message": "This league is too large. Try reducing the maximum number of teams, or the players per team",
                    "form": NewLeagueForm(),
                })
            # adds the league administrator as the current user
            league.admin = request.user
            # creates a random 8 digit league code that can be used by others to join a league
            leaguecode = uuid4().hex[:8]
            # checks the leaguecode is unique
            while checkLeagueCode(leaguecode):
                leaguecode = uuid4().hex[:8]
            league.leaguecode = leaguecode
            # saves the league
            league.save()
            # sets initial users team in the league
            team = Team.create(request.user, league, teamname)
            team.save()
        # runs checks on league_form and sets message for what is missing
        for field in league_form:
            if field.errors:
                message = f"Please input {field.name}"
        # checks that the user inputted a team name
        if "teamname" not in request.POST:
            message = f"Please input team name"
        # if message has been set as an error message returns view with error message displayed
        if message != '':
            return render(request, 'goalpoolapp/createleague.html', {
            "message": message,
            "form": NewLeagueForm(),
            })
        # if everything worked properly returns user to their dashboard
        else:
            return HttpResponseRedirect(reverse("goalpoolapp:index"), {
                "message": "League created successfully. Please share leaguecode: {league.leaguecode} to invite others to your league"
            })

# view for user to join already created league
@login_required
def joinleague(request):
    if request.method == "GET":
        return render(request, 'goalpoolapp/joinleague.html', {
            "form": NewTeamForm(),
        })
    else:
        # checks and validates newteamform
        team_form = NewTeamForm(data=request.POST)
        if team_form.is_valid():
            team = team_form.save(commit=False)
            # uses leaguecode to try and find league, returns error if leaguecode does not match a league
            try:
                league = League.objects.get(leaguecode=request.POST["leaguecode"])
            except:
                message = "Please input valid league code. Please contact league administrator"
                return render(request, 'goalpoolapp/joinleague.html', {
                    "message": message,
                    "form": NewTeamForm(),
            })
            # checks the user does not already have a team in this league
            leagueteams = league.leagueteams.all()
            for leagueteam in leagueteams:
                if request.user == leagueteam.manager:
                    message = "Sorry, you already have a team in this league"
                    return render(request, 'goalpoolapp/joinleague.html', {
                        "message": message,
                        "form": NewTeamForm(),
                    })
            # checks the league is not full
            if leagueteams.count() >= league.teamlimit:
                message = "Sorry, this league is full. Please contact league administrator"
                return render(request, 'goalpoolapp/joinleague.html', {
                    "message": message,
                    "form": NewTeamForm(),
                })
            # saves new team in league
            team.league = league
            team.manager = request.user
            team.save()
            return HttpResponseRedirect(reverse("goalpoolapp:index"))
        else:
            message = "Please fill out form"
            return render(request, 'goalpoolapp/joinleague.html', {
                "message": message,
                "form": NewTeamForm(),
            })

@login_required
def startdraft(request, leagueid):
    league = League.objects.get(id=leagueid)
    # If the draft has not been started sets draft order and starts the league
    if league.draftstarted == False:
        teams = league.leagueteams.all()
        draftnumbers = []
        for i in range(0, len(teams)):
            draftnumbers.append(i)
        for team in teams:
            draftnumber = draftnumbers[randint(0, len(draftnumbers)-1)]

goalpoolapp/templates/goalpoolapp/createglobalteam.html
{% extends "goalpoolapp/layout.html" %}

{% load static %}
{% block title %}
    Create Classic Team
{% endblock %}
{% block body %}
<script src="{% static 'goalpoolapp/globalcreate.js' %}" defer></script>
<div id="main-page-content-container">
    <div id="main-page-content">
        <h2>Create Global Team</h2>
        <p> You can pick 10 players during the group stages, then 8 players during the second round, 4 players in the quarter finals, 2 players in the semi finals, and just one in the finals. Choose carefully!</p>
        <div class="leagueinformation">
            <div class="form-container">
                {% csrf_token %}
                <div class="form-group centeredinput">
                    <input class="form-control" type="text" name="teamname" placeholder="Your Team Name" autocomplete="off" id="globalteamname">
                    <h5>Pick a player</h5>
                    <input type="hidden" value="19" id="leagueid">
                    <div class="form-group draftselect">
                        <label for="teamselect" class="label teamlabel">Select a club</label>
                        <select id="globalteamselect" class="form-control"></select>
                    </div>
                    <div id="globalplayers">
                    </div>
                </div>
            </div>
            <div id="globalteamtable">
                <div class="form-container">
                    <h5>Team Roster</h5>
                    <table class="playerleaguetable" id="pickplayertable">
                        <tr>
                            <th></th>
                            <th>Player Name</th>
                            <th>Plays For</th>
                            <th>Current Goals</th>
                        </tr>
                    </table>
                </div>
            </div>
    </div>
    <span class="button" id="teamsubmit">Create Team</span>
</div>

<!-- <script>
    console.log("{% url 'goalpoolapp:globalleague' %}")
</script> -->

{% endblock %}

goalpoolapp/templates/goalpoolapp/globalleague.html
{% extends "goalpoolapp/layout.html" %}

{% load static %}
{% block title %}
    Classic League
{% endblock %}
{% block body %}
<div id="main-page-content-container">
    <div id="main-page-content">
        <h2>Welcome {{ user.username }}!</h2>
        <br>
        {% if not team %}
        <h3>You currently do not have a team registered for the Classic league</h3>
        <a class="button" href="{% url 'goalpoolapp:createglobalteam' %}">Click here to create a team</a>
        {% else %}
            <div class="leagues-container">
                <div>
                    <div class="leaguecontainer">
                        <h3>Classic League</h3>
                        <hr>
                        <div class="leagueinformation">
                            <div class="leaguetablecontainer">
                                <div class="split-flexbox">
                                    <div>
                                        <h5>{{ team.teamname }}</h5>
                                        <h6>Current Week Roster</h6>
                                    </div>
                                    <br>
                                    <div>
                                        {% if team.manager == user %}
                                        <a class="button" href="{% url 'goalpoolapp:globaltransfers' %}">Make transfers</a>
                                        {% endif %}
                                    </div>
                                    <br>
                                </div>
                                <table class="leaguetable">
                                    <tr>
                                        <th>Player Name</th>
                                        <th>Total Goals</th>
                                        <th>Current Week Goals</th>
                                    </tr>
                                    {% for player in team.players.all %}
                                    <tr {% if forloop.counter > 2 %}style="background-color: red" {% endif %}</tr>
                                        <td>{{ player.nickname }}</td>
                                        <td>{{ player.goals }}</td>
                                        <td>{{ player.currentweekgoals }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                                <br>
                                <div class="split-flexbox">
                                    <h5>
                                        Your Team's Total Goals: {{ team.totalgoals }}
                                    </h5>
                                    <h5>
                                        Current Ranking: {{ team.rank }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="leaguecontainer">
                    <h3>Rankings</h3>
                    <div>
                        {% for team in teams|dictsort:"rank" %}
                            <h5>{{ team.rank }}: <a href="{% url 'goalpoolapp:viewglobalteam' team.id %}">{{ team.teamname }}</a> managed by {{ team.manager }} - Goals:{{ team.totalgoals }}</h5>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

goalpoolapp/templates/goalpoolapp/joinleague.html
{% extends "goalpoolapp/layout.html" %}

{% load static %}
{% block title %}
    Join Draft League
{% endblock %}
{% block body %}
<div id="main-page-content-container">
    <div id="main-page-content">
        <h2>Join Existing League</h2>

        <form action="{% url 'goalpoolapp:joinleague' %}" method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == "teamname" %}
                <div class="form-group">
                    <input class="form-control" type="text" name="teamname" placeholder="Your Team Name" autocomplete="off">
                </div>
                {% endif %}
            {% endfor %}
            <div class="form-group">
                <input class="form-control" type="text" name="leaguecode" placeholder="Enter league code" autocomplete="off">
            </div>

            <input class="btn btn-primary" type="submit" value="Join League">
        </form>
    </div>
</div>

{% endblock %}

goalpoolapp/templates/goalpoolapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1">
        <meta name="description" content="A fantasy football game based around goals scored">
        <meta name="keywords" content="football, soccer, fantasy football, fantasy soccer, premier league, world cup, goals, goal pool, draft league, game">
        <meta name="author" content="Wai Lee">
        <meta charset="UTF-8">
        <script src="https://kit.fontawesome.com/8981bb8382.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="{% static 'goalpoolapp/scripts.js' %}" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.1/js.cookie.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
        <link href="{% static 'goalpoolapp/styles.css' %}?v=3" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="{% static 'goalpoolapp/siteimages/favicon.png' %}">
    </head>
    <body>
        <div style="background: url('/static/goalpoolapp/siteimages/mainimage.webp');background-size: 100%;position:fixed;width: 100%;height:  100%;z-index: -1;" class="maincontainer">
        </div>
            <header>
                <nav id="navbar">
                    <img src="{% static 'goalpoolapp/siteimages/logo.png' %}" id="site-logo">
                    {% if user.is_authenticated %}
                    <div id="nav-link-box">
                        <div class="nav-item">
                            <a class="nav-link menuitem" href="/"><strong>Home</strong></a>
                        </div>
                        <div class="nav-item" id="leaguemenu">
                            <a class="nav-link menuitem" href="{% url 'goalpoolapp:draft' %}"><strong>Draft Leagues</strong></a>
                            <div id="leaguedropdown">
                                <div class="nav-menu-container">
                                    <a class="nav-menu-item" href="{% url 'goalpoolapp:createleague' %}"><strong>Create League</strong></a>
                                    <a class="nav-menu-item" href="{% url 'goalpoolapp:joinleague' %}"><strong>Join League</strong></a>
                                </div>
                            </div>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link menuitem" href="{% url 'goalpoolapp:globalleague' %}"><strong>Classic League</strong></a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link menuitem" href="{% url 'goalpoolapp:settings' %}"><strong>Settings</strong></a>
                        </div>
                    </div>
                    <div class="nav-item">
                        <a id="logoutbutton" href="{% url 'goalpoolapp:logoutuser' %}"><strong>Logout</strong></a>
                    </div>
                    <i class="fa-solid fa-bars fa-2xl" id="hamburgericon"></i>
                    {% else %}
                    <div class="nav-item">
                        <a id="loginbutton" href="{% url 'goalpoolapp:loginuser' %}"><strong>Login</strong></a>
                    </div>
                    {% endif %}
                </nav>
                <nav id="hamburgermenu">
                    <div class="nav-item">
                        <i class="fa-solid fa-x fa-2xl hamburgerlink" id="closeicon"></i>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="draftlinksbox">
                            <a class="hamburgerlink" href="/">Home</a>
                        </div>
                        <div class="draftlinksbox">
                            <div>
                                <i class="fa-solid fa-angle-down fa-2xl"id="draftmenudown"></i>
                                <i class="fa-solid fa-angle-up fa-2xl" id="draftmenuup"></i>
                            </div>
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:draft' %}">Draft Leagues</a>
                        </div>
                        <div id="draftleagueitems">
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:createleague' %}"><strong>Create League</strong></a>
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:joinleague' %}"><strong>Join League</strong></a>
                        </div>
                        <div class="draftlinksbox">
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:globalleague' %}">Global League</a>
                        </div>
                        <div class="draftlinksbox">
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:settings' %}">Settings</a>
                        </div>
                        <div class="draftlinksbox">
                            <a class="hamburgerlink" href="{% url 'goalpoolapp:logoutuser' %}">Logout</a>
                        </div>
                    {% endif %}
                </nav>
            </header>
            <main>
                {% if message %}
                <div id="messagebox">
                    <div id="message">{{ message }}</div>
                </div>
                {% endif %}
                {% block body %}
                {% endblock %}
            </main>
            <footer>
                <div id="footercontentcontainer">
                    <!-- Three link containers to make three columns of links -->
                    <div class="footerlinkscontainer">
                        <!-- links to other pages on site -->
                        <img src="{% static 'goalpoolapp/siteimages/logo.png' %}" id="footer-logo">
                        <p id="copyright-notice">&copy;Wai Lee, all rights reserved </p>
                    </div>

                </div>
                <!-- legal & social media links placed in a container for layout purposes -->
                <div id="socialmedialinkscontainer">
                    <a href = "mailto: footballgoalpool@gmail.com"><i class="fa-solid fa-envelope"><span>For any questions or enquiries send us an email</span></i></a>

                </div>
            </footer>
    </body>
</html>

goalpoolapp/templates/goalpoolapp/login.html
{% extends "goalpoolapp/layout.html" %}
{% block title %}
    Login
{% endblock %}
{% block body %}
    <div id="main-page-content-container">
        <div id="main-page-content">
            <h2>Login</h2>

            {% if message %}
                <div>{{ message }}</div>
            {% endif %}

            <form action="{% url 'goalpoolapp:loginuser' %}" method="post" class="form">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username" autocomplete="off">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <input class="btn btn-primary" type="submit" value="Login">
            </form>

            Don't have an account? <a href="{% url 'goalpoolapp:register' %}">Register here.</a>
        </div>
    </div>
{% endblock %}

goalpoolapp/templates/goalpoolapp/success.html
{% extends "goalpoolapp/layout.html" %}

{% load static %}
{% block title %}
    Success
{% endblock %}
{% block body %}

<div id="main-page-content-container">
    <div id="main-page-content">
        <h2>Your Password Was Changed Successfully</h2>
    </div>
</div>

{% endblock %}